Milestone 2: Add/remove and edit
yonas44/Todo-list_webpack pull request #2
Opened 2022-11-02 18:53 UTC by yonas44

- An add module to add new tasks to the list.
- A task removal module to remove a specific task.
- A module to remove all checked tasks.

Thank you for reviewing my PR!

2022-11-02 19:34 UTC, Nyame-Wolf requested changes
# STATUS: REQUIRED CHANGES :recycle: 

Hi @yonas44  :wave: 

Your project page is looking fantastic so far :star_struck: ! 

However, there is still some room for improvement, that can help you have better code and make your project professional :sunglasses: 

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

## Highlights :sparkles:

- Great work using the right GitHub Flow :100: 
- Edit functionality implemented and working well
- Items saving to the local storage
- Items checking `true` or `false` upon checking the checkbox
- Commits are descriptive and meaningful :+1: 
- Project Documentation (PR, README) is professional :necktie: 

Congrats on your work so far! :clap:  

## Required Changes ♻️

There are some issues that you still need to work on to go to the next project, but you are almost there! 
_For more information, check the comments under the review :arrow_down:_

## Optional suggestions :ballot_box_with_check: 

_Every comment with the **[OPTIONAL]** prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can improve the quality of your code :100:_

Happy coding and keep it up! :raised_hands: 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
  Please, remember to tag me **@Nyame-Wolf**  in your question so I can receive the notification.

  **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

  _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2022-11-02 19:34 UTC, Nyame-Wolf commented on src/modules/taskLoader.js
> +        dots.className = 'bi bi-three-dots-vertical';
I suggest you add a delete method for an individual task. Currently this three dots don't do anything. Its part of the [requirements](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/m3_add_remove.md) having a delete method, not one that clears all completed, but one that removes individual items.
see this video

https://user-images.githubusercontent.com/48546992/199582810-ace80120-5aee-4b09-8a43-d90b5ca21319.mov

Below is the highlighted requirement:

<img width="1676" alt="Screenshot 2022-11-02 at 22 10 48" src="https://user-images.githubusercontent.com/48546992/199583569-77862c54-9bf0-48d4-8124-8ef024aa0325.png">

2022-11-02 19:34 UTC, Nyame-Wolf commented on src/modules/taskLoader.js
> +      taskEditor(text, index, tasks);
Kindly note that as per the instructions your indexes should match the items. meaning if i have one `1` tem on the array, its index is `1` as per the instructions
<img width="1676" alt="Screenshot 2022-11-02 at 22 10 48" src="https://user-images.githubusercontent.com/48546992/199584408-13cbfff9-e15c-417f-a31b-4b807376eb09.png">

As per the screenshot attached below, your indexes start from `zero` `0`
<img width="1664" alt="Screenshot 2022-11-02 at 22 29 58" src="https://user-images.githubusercontent.com/48546992/199585383-8f762db1-9a05-40a6-87b4-e417d869f6e0.png">

2022-11-03 15:16 UTC, yonas44 commented
https://user-images.githubusercontent.com/72081991/199760340-4012400f-a38f-48b3-918d-5b34d0b31334.mp4

2022-11-03 15:19 UTC, yonas44 commented
Hello @Nyame-Wolf, so I tried to attach a video showing how I was able to remove a specific task, which I took from the actual design form [minimalist](https://web.archive.org/web/20180320194056/http://www.getminimalist.com:80/) page it self, but I addressed to the other issue you mentioned and thank you for your feedback.🙏

2022-11-03 15:33 UTC, roshan-bajgain approved these changes
Hi @yonas44, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-03 16:17 UTC, merged